### PR TITLE
feat: fallback to theme accent color when no notification thumb available

### PR DESCRIPTION
**Pull request by Bnyro**

### CODE REVIEW

**Comment by SuhasDissa** [comment]
This doesn't look good. At least on my phone.

| Before | After |
| --- | --- |
|   | |

**Comment by SuhasDissa** [comment]
This looks pretty good on the emulator imo

| Before | After |
| --- | --- |
|  |  |

**Comment by Bnyro** [comment]
Oh right, we probably should make this Android 13 and up only?

**Comment by Bnyro** [comment]
I didn't consider some devices don't use the new MD3 music notification

**Comment by Bnyro** [comment]
Or since the notification style varies depending on the ROM, we should add an option for it maybe? I don't think there's a way to figure out if the notification image is used as a small image or as a large thumbnail that covers the whole notification.

**Comment by SuhasDissa** [comment]
Adding an option for that would be good. Despite being on the same Android version, different phones have different media notification designs. Therefore, plain colored album art may or may not look good on different phones.

**Review by SuhasDissa — APPROVED** [review]

**Pull request merged**
